export const FETCH_MAKE = 'FETCH_MAKE'
export const RECEIVE_MAKE = 'RECEIVE_MAKE'
export const RECEIVE_MAKE_FAILED = 'RECEIVE_MAKE_FAILED'

export const FETCH_MODEL = 'FETCH_MODEL'
export const RECEIVE_MODEL = 'RECEIVE_MODEL'
export const RECEIVE_MODEL_FAILED = 'RECEIVE_MODEL_FAILED'

export const FETCH_VERSION = 'FETCH_VERSION'
export const RECEIVE_VERSION = 'RECEIVE_VERSION'
export const RECEIVE_VERSION_FAILED = 'RECEIVE_VERSION_FAILED'